### ISSUE TITLE
Tests for button.test.ts fails

### ISSUE THREAD

**Issue by megoth** [solid/solid-ui#227]
Seems that I've missed something when setting up the new test setup, I suspect it has something to do with jest and JSDom. Currently 19 tests fail:

```
When add button is clicked › bar is filled

    expect(received).toEqual(expected) // deep equality

    Expected: 6
    Received: 0

      74 |   })
      75 |   it('bar is filled', () => {
    > 76 |     expect(bar.childNodes.length).toEqual(barButtons.length)
         |                                   ^
      77 |   })
      78 |   for (let i = 0; i < barButtons.length; i++) {
      79 |     it(`Bar contains a "${barButtons[i]}" button`, () => {

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:76:35)

  ● When add button is clicked › Bar contains a "Add Person" button

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:80:14)

  ● When add button is clicked › Bar contains a "Add Group" button

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:80:14)

  ● When add button is clicked › Bar contains a "Add Everyone" button

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:80:14)

  ● When add button is clicked › Bar contains a "Anyone logged In" button

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:80:14)

  ● When add button is clicked › Bar contains a "A Software Agent (bot)" button

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:80:14)

  ● When add button is clicked › Bar contains a "A Web App (origin)" button

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:80:14)

  ● When "Add Person" button is clicked › bar is simplified

    TypeError: Cannot read property 'click' of undefined

      92 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      93 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 94 |     buttonToClick.click()
         |                   ^
      95 |   })
      96 |   it('bar is simplified', () => {
      97 |     // expect(bar.childNodes.length).toEqual(1) ???

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:94:19)

  ● When "Add Person" button is clicked › bar is simplified

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 0

       96 |   it('bar is simplified', () => {
       97 |     // expect(bar.childNodes.length).toEqual(1) ???
    >  98 |     expect(bar.childNodes.length).toEqual(2)
          |                                   ^
       99 |   })
      100 |   it('Bar still contains the button that was clicked', () => {
      101 |     expect(getButtonName(bar.childNodes[0])).toEqual(barButtons[buttonIndex])

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:98:35)

  ● When "Add Person" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'click' of undefined

      92 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      93 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 94 |     buttonToClick.click()
         |                   ^
      95 |   })
      96 |   it('bar is simplified', () => {
      97 |     // expect(bar.childNodes.length).toEqual(1) ???

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:94:19)

  ● When "Add Person" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:101:12)

  ● When "Add Person" button is clicked › Bar now contains askName form

    TypeError: Cannot read property 'click' of undefined

      92 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      93 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 94 |     buttonToClick.click()
         |                   ^
      95 |   })
      96 |   it('bar is simplified', () => {
      97 |     // expect(bar.childNodes.length).toEqual(1) ???

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:94:19)

  ● When "Add Person" button is clicked › Bar now contains askName form

    TypeError: Cannot read property 'tagName' of undefined

      102 |   })
      103 |   it('Bar now contains askName form', () => {
    > 104 |     expect(bar.childNodes[1].tagName).toEqual('DIV')
          |                              ^
      105 |   })
      106 | })
      107 |

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:104:30)

  ● When "Add Group" button is clicked › bar is simplified

    TypeError: Cannot read property 'click' of undefined

      115 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      116 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 117 |     buttonToClick.click()
          |                   ^
      118 |   })
      119 |   it('bar is simplified', () => {
      120 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:117:19)

  ● When "Add Group" button is clicked › bar is simplified

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 0

      118 |   })
      119 |   it('bar is simplified', () => {
    > 120 |     expect(bar.childNodes.length).toEqual(2)
          |                                   ^
      121 |   })
      122 |   it('Bar still contains the button that was clicked', () => {
      123 |     expect(getButtonName(bar.childNodes[0])).toEqual(barButtons[buttonIndex])

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:120:35)

  ● When "Add Group" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'click' of undefined

      115 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      116 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 117 |     buttonToClick.click()
          |                   ^
      118 |   })
      119 |   it('bar is simplified', () => {
      120 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:117:19)

  ● When "Add Group" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:123:12)

  ● When "Add Group" button is clicked › Bar now contains askName form

    TypeError: Cannot read property 'click' of undefined

      115 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      116 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 117 |     buttonToClick.click()
          |                   ^
      118 |   })
      119 |   it('bar is simplified', () => {
      120 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:117:19)

  ● When "Add Group" button is clicked › Bar now contains askName form

    TypeError: Cannot read property 'tagName' of undefined

      124 |   })
      125 |   it('Bar now contains askName form', () => {
    > 126 |     expect(bar.childNodes[1].tagName).toEqual('DIV')
          |                              ^
      127 |   })
      128 | })
      129 |

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:126:30)

  ● When "Add Bot" button is clicked › bar is simplified

    TypeError: Cannot read property 'click' of undefined

      137 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      138 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 139 |     buttonToClick.click()
          |                   ^
      140 |   })
      141 |   it('bar is simplified', () => {
      142 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:139:19)

  ● When "Add Bot" button is clicked › bar is simplified

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 0

      140 |   })
      141 |   it('bar is simplified', () => {
    > 142 |     expect(bar.childNodes.length).toEqual(2)
          |                                   ^
      143 |   })
      144 |   it('Bar still contains the button that was clicked', () => {
      145 |     expect(getButtonName(bar.childNodes[0])).toEqual(barButtons[buttonIndex])

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:142:35)

  ● When "Add Bot" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'click' of undefined

      137 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      138 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 139 |     buttonToClick.click()
          |                   ^
      140 |   })
      141 |   it('bar is simplified', () => {
      142 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:139:19)

  ● When "Add Bot" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:145:12)

  ● When "Add Bot" button is clicked › Bar now contains askName form

    TypeError: Cannot read property 'click' of undefined

      137 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      138 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 139 |     buttonToClick.click()
          |                   ^
      140 |   })
      141 |   it('bar is simplified', () => {
      142 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:139:19)

  ● When "Add Bot" button is clicked › Bar now contains askName form

    TypeError: Cannot read property 'tagName' of undefined

      146 |   })
      147 |   it('Bar now contains askName form', () => {
    > 148 |     expect(bar.childNodes[1].tagName).toEqual('DIV')
          |                              ^
      149 |   })
      150 | })
      151 | describe('When "Add App" button is clicked', () => {

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:148:30)

  ● When "Add App" button is clicked › bar is simplified

    TypeError: Cannot read property 'click' of undefined

      158 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      159 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 160 |     buttonToClick.click()
          |                   ^
      161 |   })
      162 |   it('bar is simplified', () => {
      163 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:160:19)

  ● When "Add App" button is clicked › bar is simplified

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 0

      161 |   })
      162 |   it('bar is simplified', () => {
    > 163 |     expect(bar.childNodes.length).toEqual(2)
          |                                   ^
      164 |   })
      165 |   it('Bar still contains the button that was clicked', () => {
      166 |     expect(getButtonName(bar.childNodes[0])).toEqual(barButtons[buttonIndex])

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:163:35)

  ● When "Add App" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'click' of undefined

      158 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      159 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 160 |     buttonToClick.click()
          |                   ^
      161 |   })
      162 |   it('bar is simplified', () => {
      163 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:160:19)

  ● When "Add App" button is clicked › Bar still contains the button that was clicked

    TypeError: Cannot read property 'tagName' of undefined

      15 |
      16 | function getButtonName (element: HTMLElement): string {
    > 17 |   expect(element.tagName).toEqual('BUTTON')
         |                  ^
      18 |   expect((element.childNodes[0] as HTMLElement).tagName).toEqual('IMG')
      19 |   return (element.childNodes[0] as HTMLImageElement).title
      20 | }

      at getButtonName (test/unit/acl/add-agent-buttons.test.ts:17:18)
      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:166:12)

  ● When "Add App" button is clicked › Bar now contains apss table

    TypeError: Cannot read property 'click' of undefined

      158 |     bar = agentButtons.childNodes[1] as HTMLDivElement
      159 |     const buttonToClick = bar.childNodes[buttonIndex] as HTMLButtonElement
    > 160 |     buttonToClick.click()
          |                   ^
      161 |   })
      162 |   it('bar is simplified', () => {
      163 |     expect(bar.childNodes.length).toEqual(2)

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:160:19)

  ● When "Add App" button is clicked › Bar now contains apss table

    TypeError: Cannot read property 'tagName' of undefined

      167 |   })
      168 |   it('Bar now contains apss table', () => {
    > 169 |     expect(bar.childNodes[1].tagName).toEqual('DIV')
          |                              ^
      170 |   })
      171 | })
      172 |

      at Object.<anonymous> (test/unit/acl/add-agent-buttons.test.ts:169:30)
```

**Comment by megoth** [comment]
When installing, I spotted the following:

```
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.1.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
```

**Comment by michielbdejong** [comment]
I can see master is broken in https://travis-ci.org/solid/solid-ui/builds/656903891, looking into it now.

**Comment by michielbdejong** [comment]
Tests pass on Travis now, with the fixes I made in https://github.com/solid/solid-ui/pull/231. Can you see how your local setup is different from https://github.com/solid/solid-ui/blob/master/.travis.yml?
Maybe try cloning this repo into a fresh folder (outside your mashlib-dev setup) and running the tests there?

**Comment by megoth** [comment]
This was resolved in https://github.com/solid/solid-ui/pull/231 for some reason, so I'll close this 😸
