### ISSUE TITLE
"Multiple records of your participation" error in Partcipation object 

### ISSUE THREAD

**Issue by timbl** [solid/solid-ui#323]
A race condition of some sort leads to two participation records with the same date time
and the id just 10 apart so very close 1 after the other

Maybe two concurrent calls to preferences code

This is is in:
/solid-ui/src/pad.js

**Comment by timbl** [comment]
See related:

```
Error: Error recording your partipation: Exception in update: Error: Update: Can't make changes in uneditable <https://solidos.solid.community/Team/SolidOs%20team%20chat/index.ttl> Error: Update: Can't make changes in uneditable <https://solidos.solid.community/Team/SolidOs%20team%20chat/index.ttl> undefined Error: Update: Can't make changes in uneditable <https://solidos.solid.community/Team/SolidOs%20team%20chat/index.ttl> undefined at e.value (https://solidos.solid.community/mashlib.min.js:1:28590) undefined at https://solidos.solid.community/mashlib.min.js:17:8932 undefined at new Promise (<anonymous>) undefined at Object.a.pad.participationObject (https://solidos.solid.community/mashlib.min.js:17:8452) undefined at https://solidos.solid.community/mashlib.min.js:128:215444
```

**Comment by timbl** [comment]
Basically need to be aware of whether the user can (a) read and (b) write, for each of 1. The local config file 2. Their private config file

**Comment by DickVG** [comment]
I noticed the same error _"Error: Multiple records of your participation"_ on my Profile Contact Card. How to solve this Bug?
When I click the Contacts Icon I see twice my name. How to delete at least one of them?
