### ISSUE TITLE
storybook build broken

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-ui#356]
This is probably an incompatibility with webpack 5, but I updated the dependencies and now I get:
```sh
$ npm run build-storybook

> solid-ui@2.3.0 build-storybook /Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui
> build-storybook  --output-dir ./examples/storybook

info @storybook/html v6.0.27
info 
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Compiling manager..
/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:118
			throw new TypeError(
			^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:118:10)
    at /Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/terser-webpack-plugin/dist/index.js:571:67
    at SyncHook.eval [as call] (eval at create (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:89:1)
    at SyncHook.lazyCompileHook (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:667:29
    at eval (eval at create (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Array.<anonymous> (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/@storybook/core/node_modules/webpack/lib/DllReferencePlugin.js:72:15)
    at Storage.finished (/Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/michiel/gh/solid/mashlib-dev/workspaces/solid-ui/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solid-ui@2.3.0 build-storybook: `build-storybook  --output-dir ./examples/storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solid-ui@2.3.0 build-storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michiel/.npm/_logs/2020-10-26T10_57_06_651Z-debug.log

**Comment by michielbdejong** [comment]
I temporarily removed build-storybook from `npm run build` until this is fixed.

**Comment by angelo-v** [comment]
Storybook seems not to support webpack 5 yet. (https://github.com/storybookjs/storybook/issues/9216) Can we downgrade back to 4, or why is 5 needed?

**Comment by michielbdejong** [comment]
We certainly can, will do!
